/***************************************************************************
                          komport.h  -  Komport Serial Port Communicator
                             -------------------
    begin                : Mon Feb 17 2003
    copyright            : (C) 2003 by Mike Sharkey
    email                : michael@sharkey.servebeer.com
    ported to Qt6         : 2026
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KOMPORT_H
#define KOMPORT_H

#include <QMainWindow>
#include <QUrl>
#include <QString>
#include <QStringList>
#include <QList>

class QSettings;
class QAction;
class QMenu;
class QToolBar;
class QSplitter;
class QComboBox;
class QLabel;

// forward declaration of the Komport classes
class KomportDoc;
class KomportView;
// GCC -Wsfinae-incomplete= fix (2026, revised after a Codex adversarial
// review of an earlier attempt - see TODO.md section 0.9 addendum): this
// class declares a slot taking KomportView* (slotViewModified() below), and
// moc-generated code for that does a completeness-dependent QMetaType trait
// check on KomportView. CMake AUTOMOC bundles every mocced header's
// generated code into one mocs_compilation.cpp translation unit, so if some
// *other* moc-generated file needing the same check ends up processed
// before this class's own KomportView becomes complete there, GCC 16+
// flags the inconsistent answer. Q_MOC_INCLUDE tells moc itself to add
// komportview.h's #include to *this* class's own generated moc_komport.cpp
// - unlike a plain #include in this header (the first attempt, reverted:
// it only accidentally protected other forward-declaring headers bundled
// after this one, and broke if AUTOMOC ever bundled them first instead),
// this fixes the completeness window at its actual source, independent of
// bundling order, without pulling komportview.h's full contents (and its
// own transitive includes) into every translation unit that includes this
// header.
Q_MOC_INCLUDE("komportview.h")
class KomportHexView;
class KomportMacroBar;
class KomportSessionLogger;

/**
  * The base class for Komport application windows. It sets up the main
  * window and reads the config file as well as providing a menubar, toolbar
  * and statusbar. An instance of KomportView creates your center view, which is connected
  * to the window's Doc object.
  *
  * Ported from KMainWindow/KDE session management to a plain QMainWindow;
  * see CLAUDE.md and TODO.md for what that carried over vs. deliberately
  * dropped (KDE crash-recovery/session restore had no real content to
  * restore in the first place).
  *
  * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
  */
class KomportApp : public QMainWindow
{
  Q_OBJECT

  friend class KomportView;

  public:
    /** construtor of KomportApp, calls all init functions to create the application. */
    explicit KomportApp(QWidget* parent=nullptr);
    ~KomportApp() override;
    /** opens a file specified by commandline option */
    void openDocumentFile(const QUrl& url=QUrl());
    /** returns a pointer to the current document connected to the main window instance and is used by
     * the View class to access the document object's methods
     */
    KomportDoc *getDocument() const;
    /** get the persistent settings object */
    QSettings* getConfig();

  protected:
    /** save general options: bar positions/visibility, geometry, recent file list, connection settings */
    void saveOptions();
    /** read general options again and initialize all variables like the recent file list */
    void readOptions();
    /** initializes the QActions of the application */
    void initActions();
    /** builds the menu bar */
    void initMenus();
    /** builds the toolbar */
    void initToolBar();
    /** sets up the statusbar for the main window */
    void initStatusBar();
    /** initializes the document object of the main window that is connected to the view in initView(). */
    void initDocument();
    /** creates the centerwidget of the main window and sets it as the view */
    void initView();
    /** builds the bottom macro/quick-command bar */
    void initMacroBar();
    /** rebuilds the "Upload recent file..." submenu from mRecentFiles */
    void rebuildRecentFilesMenu();
    /** add a URL to the recent-files list */
    void addRecentFile(const QUrl& url);
    /** asks to save modifications, then accepts/rejects the close */
    void closeEvent(QCloseEvent *event) override;
    /** watches mainToolBar for QEvent::Leave, to reset hoverHintLabel back
     *  to "Ready." once the mouse leaves the toolbar entirely (icon-to-icon
     *  transitions inside the toolbar are handled directly by the
     *  QAction::hovered() connections in initToolBar() instead) */
    bool eventFilter(QObject *watched, QEvent *event) override;

    /** seeds a handful of vendor-preset profiles (Cisco, HP 1920/1950,
     *  Aruba CX, ...) with well-known console defaults, so there's something
     *  useful to pick from on a fresh install. Tracked per preset *name* via
     *  the "SeededProfileNames" setting (not a single one-shot flag) so a
     *  later code update can add/fix a preset and have it actually reach an
     *  install that already ran this before - while still never overwriting
     *  a same-named profile the user already has, and never resurrecting
     *  one they deliberately deleted. */
    void seedBuiltinProfiles();
    /** resolves which device profile to start with (migrating pre-profile
     *  flat settings into a "Default" profile on first run under this
     *  feature, if none exist yet), populates profileCombo and loads it */
    void initProfiles();
    /** names of all profiles currently stored under the "Profiles" group */
    QStringList profileNames() const;
    /** repopulates profileCombo from profileNames(), optionally selecting _selectName */
    void refreshProfileCombo(const QString &_selectName = QString());
    /** writes the current strDevice.../strLineEnding/macroBar state into
     *  Profiles/_name, and remembers it as the last-used profile */
    void saveProfile(const QString &_name);
    /** applies strDevice.../strLineEnding to the serial port, view and
     *  line-ending combo - shared by initProfiles() and loadProfile() */
    void applyConnectionSettings();
    /** refreshes the permanent "current settings" label in the status bar
     *  footer from strDevice/strBaudRate/strDataBits/strParity/strStopBits/
     *  strLineEnding - call after anything that changes them */
    void updateConnectionStatusLabel();

  public slots:
    /** loads Profiles/_name into strDevice... and macroBar, then applies it
     *  (cleanly closing/reopening the serial port) - also usable as a
     *  direct slot target for profileCombo's textActivated signal */
    void loadProfile(const QString &_name);
    /** saves the current settings under profileCombo's current text */
    void slotSaveProfile();
    /** deletes the profile currently selected in profileCombo (asks to confirm) */
    void slotDeleteProfile();
    /** open a new application window by creating a new instance of KomportApp */
    void slotFileNewWindow();
    /** clears the document in the actual view to reuse it as the new document */
    void slotFileNew();
    /** upload a file (originally labelled "Open") */
    void slotFileOpen();
    /** upload a file from the recent files menu */
    void slotFileOpenRecent(const QUrl& url);
    /** download a file (originally labelled "Save") */
    void slotFileSave();
    /** download a file to a chosen name */
    void slotFileSaveAs();
    /** asks for saving if the file is modified, then closes the actual file and window*/
    void slotFileClose();
    /** print the actual file */
    void slotFilePrint();
    /** closes all open windows by calling close() on each top-level KomportApp window */
    void slotFileQuit();
    /** put the marked text/object into the clipboard and remove it from the document */
    void slotEditCut();
    /** put the marked text/object into the clipboard */
    void slotEditCopy();
    /** paste the clipboard into the document */
    void slotEditPaste();
    /** toggles the toolbar */
    void slotViewToolBar();
    /** toggles the statusbar */
    void slotViewStatusBar();
    /** show preferences form */
    void slotShowPreferences();
    /** changes the statusbar contents for the standard label permanently, used to indicate current actions. */
    void slotStatusMsg(const QString &text);
    /** document has been changed */
    void slotDocumentModified();
    /** the serial port failed to apply its settings, or reported an error
     *  while open - surfaces KomportSerial::settingsFailed() to the user
     *  instead of leaving it as a qWarning() only they'd have to go
     *  looking for. */
    void slotSerialSettingsFailed(const QString &_reason);
    /** No descriptions */
    void slotViewModified(KomportView*);
    /** toggles the hex monitor split-screen panel */
    void slotViewHexMonitor(bool checked);
    /** send a macro bar command (plus the configured line ending) */
    void slotMacroTriggered(const QString &command);
    /** toggles session logging - prompts for a file to start, if not already logging */
    void slotToggleRecording(bool checked);
    /** apply a line-ending choice ("CR"/"LF"/"CR+LF") from the toolbar dropdown */
    void slotLineEndingChanged(const QString &text);

  private:
    /** the persistent settings object of the application */
    QSettings *config;
    QString strDevice;
    QString strBaudRate;
    QString strFlowControl;
    QString strRxQueue;
    QString strFlushRate;
    QString strStartBits;
    QString strDataBits;
    QString strStopBits;
    QString strParity;
    QString strEmulation;
    QString strScrollBuffer;
    QString strLineEnding;
    /** name of the currently active device profile, or empty if none
     *  (e.g. it was just deleted) - see initProfiles()/loadProfile() */
    QString mCurrentProfile;
    KomportView *view;
    /** doc represents your actual document and is created only once. */
    KomportDoc *doc;
    /** recently uploaded/downloaded files */
    QList<QUrl> mRecentFiles;
    /** set by slotSerialSettingsFailed(), checked (and reset) by
     *  loadProfile()/slotShowPreferences() so their own trailing "Loaded
     *  profile ..."/"Ready." status message doesn't immediately overwrite
     *  a serial error that was just reported synchronously while applying
     *  the new settings (KomportSerial::open()/applyPortSettings() can
     *  emit settingsFailed() from inside setDeviceName()/setFraming()/.../
     *  open(), all called from within those two methods). */
    bool mSerialErrorPending = false;

    // Actions
    QAction* fileNewWindow;
    QAction* fileOpen;
    QAction* fileSave;
    QAction* fileClose;
    QAction* filePrint;
    QAction* fileQuit;
    QAction* editCut;
    QAction* editCopy;
    QAction* editPaste;
    QAction* viewToolBar;
    QAction* viewStatusBar;
    QAction* showPreferences;
    /** toggles the hex monitor pane */
    QAction* viewHexMonitor;
    /** toggles session logging */
    QAction* recordSession;
    /** saves the current settings under profileCombo's current text */
    QAction* profileSave;
    /** deletes the profile selected in profileCombo */
    QAction* profileDelete;

    // Menus/toolbar
    QMenu* fileOpenRecentMenu;
    QToolBar* mainToolBar;
    /** CR/LF/CR+LF chooser for the Return key and macro commands */
    QComboBox* lineEndingCombo;
    /** device profile picker - select an existing entry to load it, or
     *  type a new name and click profileSave to create one */
    QComboBox* profileCombo;
    /** permanent status-bar label showing the active device/framing/line-ending */
    QLabel* connectionStatusLabel;
    /** left-hand status-bar label showing toolbar-icon hover hints and
     *  "Ready." when idle - a real ("normal", addWidget()) status-bar
     *  widget with QSizePolicy::Ignored horizontally, so its *allocated*
     *  width never depends on its current text and setText() never needs a
     *  relayout. Deliberately not driven through statusBar()->showMessage():
     *  that path's geometry recomputes lazily (a posted, deferred
     *  QEvent::LayoutRequest) and a fast sweep across adjacent toolbar
     *  icons could outrun it, clipping the new text against the still-stale
     *  narrower geometry left over from the previous one - see
     *  TODO-ARCHIVE.md section 16.4/17. */
    QLabel* hoverHintLabel;

    // Hex monitor / macro bar / session logging (new in the Qt6 port)
    QSplitter* centralSplitter;
    KomportHexView* hexView;
    KomportMacroBar* macroBar;
    KomportSessionLogger* sessionLogger;
};

#endif // KOMPORT_H
