/***************************************************************************
                          komportview.h  -  Komport Serial Port Communicator
                             -------------------
    begin                : Mon Feb 17 2003
    copyright            : (C) 2003 by Mike Sharkey
    email                : michael@sharkey.servebeer.com
    ported to Qt6         : 2026
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KOMPORTVIEW_H
#define KOMPORTVIEW_H

// include files for Qt
#include <QApplication>
#include <QClipboard>
#include <QWidget>
#include <QRect>
#include <QPixmap>

#include "komportcellarray.h"
#include "komportscrollbuffer.h"
#include "komportserial.h"
#include "komportemulation.h"
#include "komportminimap.h"

class QPrinter;
class KomportDoc;

/** The KomportView class provides the view widget for the KomportApp instance.
 * The View instance inherits QWidget as a base class and represents the view object of a KTMainWindow. As KomportView is part of the
 * docuement-view model, it needs a reference to the document object connected with it by the KomportApp class to manipulate and display
 * the document structure provided by the KomportDoc class.
 *
 * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
 */
class KomportView : public QWidget
{
  Q_OBJECT
  public:
    /** Constructor for the main view */
    explicit KomportView(QWidget *parent = nullptr);
    /** Destructor for the main view */
    ~KomportView() override;

    /** returns a pointer to the document connected to the view instance. Mind that this method requires a KomportApp instance as a parent
     * widget to get to the window document pointer by calling the KomportApp::getDocument() method.
     *
     * @see KomportApp#getDocument
     */
    KomportDoc *getDocument() const;

    /** contains the implementation for printing functionality */
    void print(QPrinter *pPrinter);
  /** Return a KonPortCellAray object which represents an array of all of the character cells on the screen. */
  KomportCellArray* cellArray();
  /** Draw a character in a cell. Does nothing if _x, _y is out of range. */
  void drawChar(QChar _c,int _x, int _y);
  /** Return a pointer to a KomportCell object from an screen _x, _y coordinate.  Will return a cell from scroll buffer as required */
  KomportCell* getCell(int _x, int _y);
  /** Re-draw a cell given and _x, _y coordinate. */
  void updateCell(int _x,int _y);
  /** Re-draw a cell given a QPoint coordinate. */
  void updateCell(QPoint _p);
  /** Get a pointer to the serial port object. */
  KomportSerial* getSerial();
  /** clear selection */
  void deselect();
  /** make a selection by cell coordinates*/
  void select(QPoint start, QPoint end, bool clip=false);
  /** has a text selection */
  bool hasSelection();
  /** set the number of lines in the scroll buffer */
  virtual void setScrollBuffer(int _sz);

  /** total rows across scrollback + the live screen, oldest scrollback
   *  row first - used by KomportMinimapScrollBar to render/scroll the
   *  whole history independent of the current scroll position. */
  int totalHistoryRows();
  /** cell at absolute row _row (0 = oldest scrollback row) across the
   *  combined scrollback+live history; nullptr if out of range. Same
   *  underlying data as getCell(), just addressed absolutely instead of
   *  relative to the current scroll position. */
  KomportCell* cellAtHistoryRow(int _col, int _row);

protected: // Protected methods
  /** key press event */
  void keyPressEvent(QKeyEvent* _e) override;
  /** key release event */
  void keyReleaseEvent(QKeyEvent* _e) override;
  /** paint event */
  void paintEvent(QPaintEvent* _e) override;
  /** timer event */
  void timerEvent(QTimerEvent* _e) override;
  /** draw a cell */
  virtual void paintCell( QPainter* _paint, int _x, int _y, QRect _bounds);
  /** calculates cell size based on font. */
  void setCellSize();
  /** resize the offscreen pixmap and refresh */
  void resizeEvent(QResizeEvent* _e) override;
  /** No descriptions */
  void mouseMoveEvent( QMouseEvent* _e ) override;
  /** No descriptions */
  void mouseReleaseEvent( QMouseEvent* _e ) override;
  /** No descriptions */
  void mousePressEvent( QMouseEvent* _e ) override;
  /** mouse wheel scrolls the scrollback, same as dragging the minimap */
  void wheelEvent( QWheelEvent* _e ) override;
 /** begin a selection by pixel coordinate */
  void selectStart( QPoint _pt );
  /** end a selection by pixel coordinate */
  void selectEnd( QPoint _pt );
  /** reset scrollbar */
  void resetScroll();
  /** grow/shrink the live grid to _newRows, keeping the column count fixed.
   *  Shrinking pushes the rows that no longer fit off the top into the
   *  scrollback buffer first (like a normal line-feed-driven scroll would),
   *  so nothing is silently discarded; growing just appends blank rows at
   *  the bottom. Adjusts the cursor position to match. Called from
   *  resizeEvent() so the terminal's row count tracks the window's height
   *  (the column count/width stays fixed, matching a classic terminal). */
  void resizeGridRows(int _newRows);
private: // Private attributes
  /** character cell array */
  KomportCellArray mCellArray;
  /** scroll buffer */
  KomportScrollBuffer mScrollBuffer;
  /** cursor time */
  int mCursorTimer;
  /** blink timer */
  int mBlinkTimer;
  /** cursor state */
  bool mCursorState;
  /** blink state */
  bool mBlinkState;
  /** offscreen buffer */
  QPixmap mPixmap;
  /** selection start */
  QPoint mSelectStart;
  /** selection end */
  QPoint mSelectEnd;
  /** performing a text selection */
  bool mInSelection;
  /** has text selection */
  bool mHasSelection;
  /** Kate-style minimap scrollbar (see komportminimap.h) - a genuine child
   *  of this widget (not a manually-positioned sibling like the original
   *  Qt3 code had it), so its position stays correct no matter what
   *  container this view itself ends up embedded in (e.g. the central
   *  QSplitter, for the hex monitor). */
  KomportMinimapScrollBar* mScrollBar;
  /** auto scroll timer for extending text selection into scroll buffer */
  int mAutoScrollTimer;
  /** for tracking mouse during selctions */
  QPoint mMousePos;
  /** carries the sub-notch remainder of wheelEvent()'s angleDelta() between
   *  events, so wheel/touchpad hardware that reports many small deltas
   *  instead of one +-120 "notch" per event still scrolls smoothly rather
   *  than needing to build up a full notch's worth in one single event */
  int mAccumWheelDelta = 0;
public slots: // Public slots
  /** notify cursor position has changde */
  void slotCursorChanged(QPoint _old, QPoint _new);
  /** a cell content has changed */
  void slotCellChanged(QPoint _p);
  /** update a row */
  void slotRowChanged(int _row);
  /** received a char */
  void slotReceivedChar(char _ch);
  /** notification that the cell array has scrolled up so we need to scroll visually */
  void slotScrolledUp();
  /** before the actual scroll takes place */
  void slotAboutToScrollUp();
  /** No descriptions */
  void slotSelectionChanged();
  /** simulated key press for inserting from clipboard, etc... */
  void slotSimKeyPressed(QChar _c);
  /** scroll bar moved */
  void slotScroll(int _value);
public: // Public attributes
  /** terminal emulation */
  KomportEmulation* mEmulation;
signals: // Signals
  /** No descriptions */
  void viewModified(KomportView*);
  /** key pressed */
  void keyPressed(QKeyEvent*);
  /** simulated key press */
  void simKeyPressed(QChar);
};

#endif // KOMPORTVIEW_H
