/***************************************************************************
                          komportdoc.h  -  Komport Serial Port Communicator
                             -------------------
    begin                : Mon Feb 17 2003
    copyright            : (C) 2003 by Mike Sharkey
    email                : michael@sharkey.servebeer.com
    ported to Qt6         : 2026
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KOMPORTDOC_H
#define KOMPORTDOC_H

// include files for Qt
#include <QObject>
#include <QString>
#include <QList>
#include <QUrl>

#include <memory>

#include "komportserial.h"
#include "sessioncontroller.h"
#include "sessionrecorder.h"

// forward declaration of the Komport classes
class KomportView;
// GCC -Wsfinae-incomplete= fix (2026) - see the matching comment in
// komport.h and TODO.md section 0.9 addendum for the full explanation.
// This class independently has the same pattern - the moc-visible
// slotUpdateAllViews()/slotViewModified()/viewModified() below all take
// KomportView* (addView()/removeView() also take it but are ordinary
// public methods, not moc-visible, so they aren't actually part of the
// problem) - proven by a Codex adversarial review to reproduce the exact
// same warning under certain AUTOMOC bundling orders - it was not hit in
// practice only because komport.h's own moc output currently happens to
// complete KomportView first in the combined translation unit, not
// because this file was actually safe.
Q_MOC_INCLUDE("komportview.h")

/**	KomportDoc provides a document object for a document-view model.
  *
  * The KomportDoc class provides a document object that can be used in conjunction with the classes KomportApp and KomportView
  * to create a document-view model for standard KDE applications based on KApplication and KMainWindow. Thereby, the document object
  * is created by the KomportApp instance and contains the document structure with the according methods for manipulation of the document
  * data by KomportView objects. Also, KomportDoc contains the methods for serialization of the document data from and to files.
  *
  * NOTE: openDocument()/saveDocument() were already unimplemented TODO stubs
  * in the original KDE3 version (no file content was ever actually read or
  * written) - this Qt6 port keeps that as-is rather than inventing new
  * document persistence that was never part of the original design.
  *
  * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
  */
class KomportDoc : public QObject
{
  Q_OBJECT
  public:
    /** Constructor for the fileclass of the application */
    explicit KomportDoc(QObject *parent);
    /** Destructor for the fileclass of the application */
    ~KomportDoc() override;

    /** adds a view to the document which represents the document contents. Usually this is your main view. */
    void addView(KomportView *view);
    /** removes a view from the list of currently connected views */
    void removeView(KomportView *view);
    /** sets the modified flag for the document after a modifying action on the view connected to the document.*/
    void setModified(bool _m=true);
    /** returns if the document is modified or not. Use this to determine if your document needs saving by the user on closing.*/
    bool isModified(){ return modified; };
    /** "save modified" - asks the user for saving if the document is modified */
    bool saveModified();
    /** deletes the document's contents */
    void deleteContents();
    /** initializes the document generally */
    bool newDocument();
    /** closes the acutal document */
    void closeDocument();
    /** loads the document by filename and format and emits the updateViews() signal */
    bool openDocument(const QUrl& url);
    /** saves the document under filename and format.*/
    bool saveDocument(const QUrl& url);
    /** returns the URL of the document */
    const QUrl& URL() const;
    /** sets the URL of the document */
	  void setURL(const QUrl& url);
    /** display name of the document ("Untitled" if the URL carries no file name) */
    QString fileName() const;
  /** get the serial port */
  KomportSerial* getSerial();
  /** the document-owned session controller bound to the serial transport
    * (SPEC-M8 6.2). It is created with the document, lives as long as it does,
    * and is destroyed before the transport. */
  SessionController* getSessionController();
  /** The document's session recorder (SPEC-M9 5.8); never null. Recording is
    *  started and stopped by the application, not by the document. */
  SessionRecorder* getSessionRecorder();
  /** Close the session: close the transport first, while the controller and the
    *  recorder are still alive, and only then finalise a running recording
    *  (SPEC-M9 5.8 - that ordering is normative, because it is what keeps the
    *  terminal `TransportClosed` event in the file). Returns the recording's
    *  report, or an empty report when nothing was being recorded. This is the
    *  operation the application's close path performs; it is a document method so
    *  that the ordering itself is testable without a window. */
  SessionRecordingReport closeSession();

  public slots:
    /** calls repaint() on all views connected to the document object and is called by the view by which the document has been changed.
     * As this view normally repaints itself, it is excluded from the paintEvent.
     */
    void slotUpdateAllViews(KomportView *sender);
  /** No descriptions */
  void slotViewModified(KomportView*);

  public:
    /** the list of the views currently connected to the document (not owned by this list) */
    static QList<KomportView*> *pViewList;

  private:
    /** the modified flag of the current document */
    bool modified;
    QUrl doc_url;
  /** serial port */
  KomportSerial mSerial;
  /** the live session recorder (SPEC-M9 5.8). Declared after `mSerial` and
    * before the controller, so that - members being destroyed in reverse
    * declaration order - the controller dies first, then the recorder, then the
    * transport, which is the order the specification fixes for the milestone. The
    * destructor resets both explicitly as well. */
  std::unique_ptr<SessionRecorder> mSessionRecorder;
  /** the session controller (SPEC-M8 6.2). Declared after mSerial and destroyed
    * explicitly first: a QObject-child arrangement is not acceptable, because
    * mSerial is a by-value member and would already be destroyed. */
  std::unique_ptr<SessionController> mSessionController;
signals: // Signals
  /** Document has changed. */
  void documentModified();
signals: // Signals
  /** No descriptions */
  void viewModified(KomportView*);
};

#endif // KOMPORTDOC_H
