/***************************************************************************
                          komportdoc.h  -  Komport Serial Port Communicator
                             -------------------
    begin                : Mon Feb 17 2003
    copyright            : (C) 2003 by Mike Sharkey
    email                : michael@sharkey.servebeer.com
    ported to Qt6         : 2026
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/

#ifndef KOMPORTDOC_H
#define KOMPORTDOC_H

// include files for Qt
#include <QObject>
#include <QString>
#include <QList>
#include <QUrl>

#include "komportserial.h"

// forward declaration of the Komport classes
class KomportView;

/**	KomportDoc provides a document object for a document-view model.
  *
  * The KomportDoc class provides a document object that can be used in conjunction with the classes KomportApp and KomportView
  * to create a document-view model for standard KDE applications based on KApplication and KMainWindow. Thereby, the document object
  * is created by the KomportApp instance and contains the document structure with the according methods for manipulation of the document
  * data by KomportView objects. Also, KomportDoc contains the methods for serialization of the document data from and to files.
  *
  * NOTE: openDocument()/saveDocument() were already unimplemented TODO stubs
  * in the original KDE3 version (no file content was ever actually read or
  * written) - this Qt6 port keeps that as-is rather than inventing new
  * document persistence that was never part of the original design.
  *
  * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team.
  */
class KomportDoc : public QObject
{
  Q_OBJECT
  public:
    /** Constructor for the fileclass of the application */
    explicit KomportDoc(QObject *parent);
    /** Destructor for the fileclass of the application */
    ~KomportDoc() override;

    /** adds a view to the document which represents the document contents. Usually this is your main view. */
    void addView(KomportView *view);
    /** removes a view from the list of currently connected views */
    void removeView(KomportView *view);
    /** sets the modified flag for the document after a modifying action on the view connected to the document.*/
    void setModified(bool _m=true);
    /** returns if the document is modified or not. Use this to determine if your document needs saving by the user on closing.*/
    bool isModified(){ return modified; };
    /** "save modified" - asks the user for saving if the document is modified */
    bool saveModified();
    /** deletes the document's contents */
    void deleteContents();
    /** initializes the document generally */
    bool newDocument();
    /** closes the acutal document */
    void closeDocument();
    /** loads the document by filename and format and emits the updateViews() signal */
    bool openDocument(const QUrl& url);
    /** saves the document under filename and format.*/
    bool saveDocument(const QUrl& url);
    /** returns the URL of the document */
    const QUrl& URL() const;
    /** sets the URL of the document */
	  void setURL(const QUrl& url);
    /** display name of the document ("Untitled" if the URL carries no file name) */
    QString fileName() const;
  /** get the serial port */
  KomportSerial* getSerial();

  public slots:
    /** calls repaint() on all views connected to the document object and is called by the view by which the document has been changed.
     * As this view normally repaints itself, it is excluded from the paintEvent.
     */
    void slotUpdateAllViews(KomportView *sender);
  /** No descriptions */
  void slotViewModified(KomportView*);

  public:
    /** the list of the views currently connected to the document (not owned by this list) */
    static QList<KomportView*> *pViewList;

  private:
    /** the modified flag of the current document */
    bool modified;
    QUrl doc_url;
  /** serial port */
  KomportSerial mSerial;
signals: // Signals
  /** Document has changed. */
  void documentModified();
signals: // Signals
  /** No descriptions */
  void viewModified(KomportView*);
};

#endif // KOMPORTDOC_H
